simlr/urls.py
from django.urls import path

from . import views

app_name = 'simlr'
urlpatterns = [
    path('', views.index, name='index'),
    path('playlist', views.playlist, name='playlist'),
    ]

thesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('simlr/', include('simlr.urls')),
    path('admin/', admin.site.urls),
]

simlr/models.py
from django.db import models

simlr/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from . import mainapp

def index(request):
    if request.session.get('redirected') is None:
        context = {
            'current_playlist_url': None,
            'seed_artist': None,
        }
    else:
        context = {
            'current_playlist_url': request.session.get('playlisturl', None),
            'seed_artist': request.session.get('seedartist', None),
        }
        request.session['redirected'] = None
        request.session['playlisturl'] = None
        request.session['seedartist'] = None
    return render(request, 'simlr/index.html', context)

def playlist(request):
    
    seedartist = request.POST['seedartist']
    request.session['seedartist'] = seedartist
    request.session['playlisturl'] = mainapp.get_youtube_playlist(seedartist)
    print(request.session['playlisturl'])
    request.session['redirected'] = True
    return HttpResponseRedirect(reverse('simlr:index'))

simlr/templates/simlr/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'simlr/main.css' %}">

    <title>Simlr</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-dark">
      <a class="navbar-brand" href="#">
	<img src="{% static 'simlr/images/logo.png' %}" alt="Logo" style="width:180px;">
      </a>
      <form class="form-inline" action="{% url 'simlr:playlist' %}" method="post">
	{% csrf_token %}
	<input class="form-control mr-sm-2" type="text" placeholder="Enter artist name" name="seedartist" value="">
	<input class="btn btn-success" type="submit" value="Create Playlist">
      </form>
    </nav>



    <div class="container h-100" >
    <h2 class="display-4 text-white">Listen to a playlist of songs from similar artists.</h2>
      <div class="row h-100 justify-content-center align-items-center">
    {% if current_playlist_url and seed_artist %}
      <iframe width="1200" height="700" src="{{current_playlist_url}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen> </iframe>
    {% elif seed_artist is not None and current_playlist_url is None %}
    <p>There was an error while generating the playlist.</p>
    {% else %}
    {% endif %}
    </div>
    </div>


  </body>
</html>